<?php

namespace MultiBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * RealisationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RealisationRepository extends EntityRepository
{
}
