realisation_index:
    path:     /
    defaults: { _controller: "MultiBundle:Realisation:index" }
    methods:  GET

realisation_show:
    path:     /{id}/show
    defaults: { _controller: "MultiBundle:Realisation:show" }
    methods:  GET

realisation_new:
    path:     /new
    defaults: { _controller: "MultiBundle:Realisation:new" }
    methods:  [GET, POST]

realisation_edit:
    path:     /{id}/edit
    defaults: { _controller: "MultiBundle:Realisation:edit" }
    methods:  [GET, POST]

realisation_delete:
    path:     /{id}/delete
    defaults: { _controller: "MultiBundle:Realisation:delete" }
    methods:  DELETE
